### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by fortitude001** [minminmsn/k8s1.13#3]
大神，我的环境是CentOS Linux release 7.1.1503 (Core),可以装k8s 1.13吗？同时，兼容的docker版本应该是哪个呢？

**Comment by minminmsn** [comment]
可以，centos7.1可以直接升级到7.5，docker版本我文档里是用的docker源，内核版本越高越好。

**Comment by fortitude001** [comment]
嗯，我内核自动升级了。
但是现在又遇到一个问题，我只用了两台机器，一个master，一个node，然后配置etcd时，无法启动成功。
报错： health check for peer d9798d9a3a4781cb could not connect: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while tr

是不是etcd集群必须用3台机器啊？还是其他原因？

**Comment by fortitude001** [comment]
> 嗯，我内核自动升级了。
> 但是现在又遇到一个问题，我只用了两台机器，一个master，一个node，然后配置etcd时，无法启动成功。
> 报错： health check for peer d9798d9a3a4781cb could not connect: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while tr
> 
> 是不是etcd集群必须用3台机器啊？还是其他原因？

我现在是etcd根本启动不起来。。

**Comment by fortitude001** [comment]
> > 嗯，我内核自动升级了。
> > 但是现在又遇到一个问题，我只用了两台机器，一个master，一个node，然后配置etcd时，无法启动成功。
> > 报错： health check for peer d9798d9a3a4781cb could not connect: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while tr
> > 是不是etcd集群必须用3台机器啊？还是其他原因？
> 
> 我现在是etcd根本启动不起来。。

之前出问题的原因是由于：我将证书在node节点又重新生成了一遍，应该使用scp -r *.* ip:/k8s/将master上生成的证书拷贝至node节点。
与几台机器无关。我使用2台机器已经完成了安装。
